/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleItem: typeof import('./src/components/ArticleItem/index.vue')['default']
    ArticleList: typeof import('./src/components/ArticleList/index.vue')['default']
    BackTop: typeof import('./src/components/global/back-top.vue')['default']
    Banner: typeof import('./src/components/public/Banner.vue')['default']
    Body: typeof import('./src/components/layout/Body.vue')['default']
    Feature: typeof import('./src/components/feature/index.vue')['default']
    FlipClock: typeof import('./src/components/FlipClock/FlipClock.vue')['default']
    Flipper: typeof import('./src/components/FlipClock/Flipper.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Loading: typeof import('./src/components/public/Loading.vue')['default']
    MenuLeft: typeof import('./src/components/global/menu-left.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setup: typeof import('./src/components/global/setup.vue')['default']
    TablePet: typeof import('./src/components/global/table-pet.vue')['default']
    TodoList: typeof import('./src/components/public/TodoList.vue')['default']
    Waves: typeof import('./src/components/global/Waves.vue')['default']
  }
}
